---
name: build

# Actions that take place on branches
# or are driven by pull-requests to the main/master branch.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# (n/a)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build-requirements.txt
        pip install -r requirements.txt
    - name: Lint
      run: |
        pre-commit run --all-files
        pylint src
    - name: Jote
      run: jote --dry-run
    - name: Build
      run: docker-compose build
